[package]
name = "counter-v2"
version = "1.0.0"
edition = "2021"

[dependencies]
casper-contract = "4.0.0"
casper-types = "4.0.1"

[[bin]]
name = "counter-v2"
path = "src/main.rs"
bench = false
doctest = false
test = false
