[package]
name = "counter-v2"
version = "1.0.0"
edition = "2021"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "counter-v2"
path = "src/main.rs"
bench = false
doctest = false
test = false
