[package]
name = "counter-call"
version = "1.0.0"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2021"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "counter-call"
path = "src/main.rs"
bench = false
doctest = false
test = false
